on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: waws-prod-dm1-173.ftp.azurewebsites.windows.net
        username: rsne\$rsne
        password: PeC8ZaEikrdaPwC9LjpqH3nBxrkiguSDJqoqdCDNhB1knCmd3B9lK5B80XZg
        protocol: ftps        
        server-dir: /site/wwwroot/
        # dry-run: true
